

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."articles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" DEFAULT ''::"text" NOT NULL,
    "text" "text" DEFAULT ''::"text",
    "layout_config" "text" DEFAULT ''::"text",
    "excerpt" "text" DEFAULT ''::"text",
    "slug" "text" DEFAULT ''::"text",
    "visibile" boolean DEFAULT true NOT NULL,
    "view_count" bigint DEFAULT '0'::bigint NOT NULL,
    "author_id" bigint
);


ALTER TABLE "public"."articles" OWNER TO "postgres";


COMMENT ON TABLE "public"."articles" IS 'Blog articles storing article data and metadata';



ALTER TABLE "public"."articles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Articles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."authors" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL,
    "username" "text" DEFAULT ''::"text",
    "email" "text" DEFAULT ''::"text",
    "bio" "text",
    "social_links" "jsonb",
    "profile_picture" "text",
    "article_count" integer DEFAULT 0,
    "slug" "text" DEFAULT ''::"text"
);


ALTER TABLE "public"."authors" OWNER TO "postgres";


COMMENT ON TABLE "public"."authors" IS 'Authors of Respectful Mother Particles';



ALTER TABLE "public"."authors" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Authors_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."article_images" (
    "id" bigint NOT NULL,
    "article_id" bigint,
    "image_id" "uuid",
    "position" smallint
);


ALTER TABLE "public"."article_images" OWNER TO "postgres";


COMMENT ON TABLE "public"."article_images" IS 'link between articles and images';



ALTER TABLE "public"."article_images" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."article_images_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."images" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "date" "date" NOT NULL,
    "url" "text",
    "alt_text" "text",
    "latitude" double precision,
    "lens_model" "text",
    "longitude" double precision,
    "camera_model" "text",
    "iso" integer,
    "shutter_speed" double precision,
    "f_number" smallint
);


ALTER TABLE "public"."images" OWNER TO "postgres";


COMMENT ON TABLE "public"."images" IS 'images for display and accompanying particles';



COMMENT ON COLUMN "public"."images"."latitude" IS 'latitude of photograph';



COMMENT ON COLUMN "public"."images"."lens_model" IS 'model of lens';



COMMENT ON COLUMN "public"."images"."longitude" IS 'longitude of photograph';



COMMENT ON COLUMN "public"."images"."iso" IS 'photo ISO value';



COMMENT ON COLUMN "public"."images"."f_number" IS 'apeture value';



ALTER TABLE ONLY "public"."articles"
    ADD CONSTRAINT "Articles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."articles"
    ADD CONSTRAINT "Articles_title_key" UNIQUE ("title");



ALTER TABLE ONLY "public"."authors"
    ADD CONSTRAINT "Authors_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."authors"
    ADD CONSTRAINT "Authors_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."article_images"
    ADD CONSTRAINT "article_images_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."articles"
    ADD CONSTRAINT "articles_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."articles"
    ADD CONSTRAINT "articles_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."authors"
    ADD CONSTRAINT "authors_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."authors"
    ADD CONSTRAINT "authors_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."images"
    ADD CONSTRAINT "images_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."article_images"
    ADD CONSTRAINT "article_images_article_id_fkey" FOREIGN KEY ("article_id") REFERENCES "public"."articles"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."article_images"
    ADD CONSTRAINT "article_images_image_id_fkey" FOREIGN KEY ("image_id") REFERENCES "public"."images"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."articles"
    ADD CONSTRAINT "articles_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "public"."authors"("id");



CREATE POLICY "Enable read access for all users" ON "public"."article_images" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."articles" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."images" FOR SELECT USING (true);



CREATE POLICY "Enable writes for all users" ON "public"."images" FOR INSERT WITH CHECK (true);



ALTER TABLE "public"."article_images" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."articles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."authors" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."images" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";












































































































































































































GRANT ALL ON TABLE "public"."articles" TO "anon";
GRANT ALL ON TABLE "public"."articles" TO "authenticated";
GRANT ALL ON TABLE "public"."articles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Articles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Articles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Articles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."authors" TO "anon";
GRANT ALL ON TABLE "public"."authors" TO "authenticated";
GRANT ALL ON TABLE "public"."authors" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Authors_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Authors_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Authors_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."article_images" TO "anon";
GRANT ALL ON TABLE "public"."article_images" TO "authenticated";
GRANT ALL ON TABLE "public"."article_images" TO "service_role";



GRANT ALL ON SEQUENCE "public"."article_images_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."article_images_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."article_images_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."images" TO "anon";
GRANT ALL ON TABLE "public"."images" TO "authenticated";
GRANT ALL ON TABLE "public"."images" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
